import java.util.*;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static List<Integer> removeEven(List<Integer> numbers) {
        if (null == numbers){
            throw new IllegalArgumentException("");
        }

        return numbers
                .stream()
                .filter((Integer theNumber)-> theNumber %2 != 0)
                .collect(Collectors.toList());
    }
    public static List<String> oddOrEven(List<Integer> numbers){
        return numbers
                .stream()
                .map((Integer integer) -> integer % 2 == 0 ? "Even" : "Odd")
                .collect(Collectors.toList());
    }


    public static void main(String[] args) {
//        System.out.println(oddOrEven(Arrays.asList(0,1)));
//        System.out.println(pluck());
    }

    public static List<String> pluck(List<Map<String, String>> pluckMap, String key) {
        if(pluckMap == null){
            throw new IllegalArgumentException("");
        }

//        return pluckMap
//                .stream()
//                .map((Map<String, String> element) -> element.containsKey(key) ? element.get(key) : element.get(null))
//                .collect(Collectors.toList());

        return pluckMap
                .stream()
                .filter((hash) -> hash.get(key) != null)
                .map((hash) -> hash.get(key))
                .collect(Collectors.toList());
    }

    public static String join(ArrayList<String> givenArray, String delimiter) {
        if (givenArray == null){
            throw new IllegalArgumentException("");
        }
        System.out.println(arrayToString(givenArray));
        return givenArray.toString();
    }

//    @Override
    public static String arrayToString(ArrayList<String> strings) {
        StringBuilder sb = new StringBuilder();
        for (String str : strings) {
            sb.append(str);
            sb.append(" ");
        }
        return sb.toString();
    }
}
